### ISSUE TITLE
Is there any way of downloading the dataset XING?

### ISSUE THREAD

**Issue by wangjialin114** [mquad/hgru4rec#1]
hi, i have noticed that your work is very interesting. I want to reproduce the results. Since the recsys challenge has closed. I have no idea to download the dataset. I would appreciate a lot if you have any suggestions?

**Comment by mquad** [comment]
Hi,
Thanks for your message. I'm sorry for earing that you and other people are having troubles in accessing the data.
I'll check if there's a way of making the dataset public again.

Cheers
Massimo

**Comment by mquad** [comment]
Apparently, the data of the 2016 version of the competition is no longer available for public usage.
BTW, the 2017 version of the same dataset is still available [here](https://recsys.xing.com/submission). First, you have to create a team and accept the challenge rules (even if the challenge is closed since a while...). Then you'll be able to download the new dataset. But hurry up since it might get closed anytime soon!

The dataset contains user interactions (interactions.csv) in the same format used in the paper. Sadly, this is not enough to ensure the exact reproducibility of the results of the paper as the data is 99% different, but I expect you'll obtain similar results. I'll run some experiments on my own when I find some spare time. LMK! :-)

**Comment by if-zz** [comment]
Hi,  i am interested in you work and want to get the data for my research.
A week ago I created a team and wait for approval. But it is still waiting for approval and not allowed me to download the data.  Is there another way to get the data or some alternatives? 
Thank you. Cordially,
Zeng

**Comment by mquad** [comment]
Hi, unfortunately I don't know any alternative way of retrieving the data. 
You may try opening an issue about the dataset at the challenge [repo](https://github.com/recsyschallenge/2016) and see if the organizers can help. 
Sorry about that :-(

**Comment by simushga** [comment]
Hi,

I understand that the Xing dataset is not available anymore. However, it would help a lot if I know the format of data. Is this a similar format to what interactions.csv looks like?

3385219031517549721,item_id1,2018-02-09 21:42:54.574,0
4532645799010716204,item_id2,2018-02-10 14:38:44.033,1
4532645799010716204,item_id3,2018-02-10 14:39:59.143,3
3072691951005999151,item_id4,2018-02-09 21:12:13.617,2

Cheers

**Comment by mquad** [comment]
The format is a tab-separated list of interactions like

user_id	item_id	interaction_type	created_at
user1	item1	1	1444154047
user1	item2	1	1445338496
user1	item3	1	1444806365

But your format can work as well, as long as you can convert it to a pandas DataFrame of interactions with integer timestamps.

Cheers
